### ISSUE TITLE
Resource temporarily unavailable (os error 35)

### ISSUE THREAD

**Issue by xinyangt9** [zhxie/stunxy#1]
ClashX前置Sock5代理端口为7891
试了包括stun.ekiga.net在内的很多stun服务器都报错Resource temporarily unavailable (os error 35)
试了Google的stun服务器报错SourceAddress missing!
请问如何解决呢
<img width="454" alt="Screen Shot 2021-01-10 at 00 56 31" src="https://user-images.githubusercontent.com/55012776/104103754-c0745980-52de-11eb-855b-c072d1fc804e.png">

**Comment by xinyangt9** [comment]
stun.ekiga.net好像时好时坏的，试几次中会有一次可以的lol

**Comment by zhxie** [comment]
I tried it, and the SOURCE-ADDRESS field is really missing from the response of Google’s STUN server.
You can try other STUN servers, such as stun.miwifi.com, stun.bige0.com and stun.stunprotocol.org.

---

我试了一下，Google 的 STUN 服务器的回执报文中确实缺少 SOURCE-ADDRESS 字段。
你可以试试别的 STUN 服务器，比如 stun.miwifi.com、stun.bige0.com 和 stun.stunprotocol.org。

**Comment by xinyangt9** [comment]
好的，谢谢回复
